title : Programming for Cultural Data Analysis
tagline: 
author :
	  name : Stephen McLaughlin
	  email : stephen.mclaughlin@utexas.edu
	  github : stevemclaugh
	  twitter : stevemclaugh
	  feedburner : feedname